"""first_empty_migration

Revision ID: a6df7c9124be
Revises:
Create Date: 2024-09-18 22:40:07.892034

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a6df7c9124be"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
