"""create_task_tadble

Revision ID: b13295f9fac2
Revises: 925f30493c24
Create Date: 2024-09-18 22:54:19.185777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b13295f9fac2"
down_revision: Union[str, None] = "925f30493c24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("FAILED", "CREATED", "RUNNING", "COMPLETED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("raised_exception_name", sa.String(), nullable=True),
        sa.Column(
            "failure_reason",
            sa.Enum(
                "MEMORY_LIMIT_EXCEEDED",
                "TIME_LIMIT_EXCEEDED",
                "WORKER_KILLED_BY_SIGNAL",
                "OTHER",
                name="taskfailurereason",
            ),
            nullable=True,
        ),
        sa.Column("traceback", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    # ### end Alembic commands ###
