version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      pip:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

    groups:
      actions: