"""First empty migration

Revision ID: 03c0f0f4b98e
Revises:
Create Date: 2023-12-22 15:55:23.335330

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "03c0f0f4b98e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
