from datetime import datetime

device_data = [
    {
        "id": "3939939393",
        "user_agent": "text",
        "browser": "text",
        "engine": "text",
        "os": "text",
        "os_version": "text",
        "device": "text",
        "cpu": "text",
        "screen": "text",
        "plugins": "text",
        "time_zone": "text",
        "language": "text",
        "created_at": datetime.now(),
    },
    {
        "id": "393449939393",
        "user_agent": "text",
        "browser": "text",
        "engine": "text",
        "os": "text",
        "os_version": "text",
        "device": "text",
        "cpu": "text",
        "screen": "text",
        "plugins": "text",
        "time_zone": "text",
        "language": "text",
        "created_at": datetime.now(),
    },
    {
        "id": "3443434",
        "user_agent": "text",
        "browser": "text",
        "engine": "text",
        "os": "text",
        "os_version": "text",
        "device": "text",
        "cpu": "text",
        "screen": "text",
        "plugins": "text",
        "time_zone": "text",
        "language": "text",
        "created_at": datetime.now(),
    },
    {
        "id": "34433434",
        "user_agent": "text",
        "browser": "text",
        "engine": "text",
        "os": "text",
        "os_version": "text",
        "device": "text",
        "cpu": "text",
        "screen": "text",
        "plugins": "text",
        "time_zone": "text",
        "language": "text",
        "created_at": datetime.now(),
    },
]
