from datetime import datetime

file_info_data = [
    {
        "is_built_in": True,
        "is_valid": True,
        "file_name": "name",
        "original_file_name": "name",
        "has_header": True,
        "delimiter": "delimeter",
        "renamed_header": "header",
        "rows_count": 6,
        "count_of_columns": 5,
        "path": "1///",
        "id": "94fd971c-fa7d-4a9b-bedf-781622dc2741",
        "created_at": datetime.now(),
        "user_id": "6d6d3c27-c39f-4fe5-a1f2-be23271e62f1",
        "mime_type": "mime type",
        "encoding": "enccoding",
        "deleted_at": None,
    },
    {
        "is_built_in": True,
        "is_valid": True,
        "file_name": "name",
        "original_file_name": "name",
        "has_header": True,
        "delimiter": "delimeter",
        "renamed_header": "header",
        "rows_count": 4,
        "count_of_columns": 54,
        "path": "..datasets/file_number_one",
        "id": "24ed931c-fa7d-4a9b-bedf-781622dc2741",
        "user_id": "5e5c3c27-c39f-4fe5-a1f2-be23271e62f1",
    },
    {
        "is_built_in": True,
        "is_valid": True,
        "file_name": "name",
        "original_file_name": "name",
        "has_header": True,
        "delimiter": "delimeter",
        "renamed_header": "header",
        "rows_count": 5,
        "count_of_columns": 1,
        "path": "..datasets/file_number_two",
        "id": "0589040a-1924-42f9-9c1d-e4c57756963f",
    },
]
