"""empty message

Revision ID: e466f24f111f
Revises: e0dfc8e7f2e8
Create Date: 2025-08-18 21:05:34.872161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e466f24f111f"
down_revision: Union[str, None] = "e0dfc8e7f2e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.drop_constraint("tasks_initiator_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("tasks", "initiator_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("initiator_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_initiator_id_fkey",
        "tasks",
        "users",
        ["initiator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("tasks", "owner_id")
    # ### end Alembic commands ###
