"""empty message

Revision ID: 4f6dd5524a28
Revises: ef62a1b9dee3
Create Date: 2025-11-11 04:58:20.025888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f6dd5524a28"
down_revision: Union[str, None] = "ef62a1b9dee3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    oauth_provider_enum = postgresql.ENUM(
        "GITHUB", "GOOGLE", name="oauthprovider", create_type=True
    )
    oauth_provider_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("oauth_provider", oauth_provider_enum, nullable=False)
    )
    op.add_column("users", sa.Column("oauth_id", sa.String(), nullable=False))
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_unique_constraint(
        "uq_user_oauth", "users", ["oauth_provider", "oauth_id"]
    )
    op.drop_column("users", "company")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    op.drop_column("users", "full_name")
    op.drop_column("users", "occupation")
    op.drop_column("users", "is_verified")
    op.drop_column("users", "country")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("occupation", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users", sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("uq_user_oauth", "users", type_="unique")
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_column("users", "oauth_id")
    op.drop_column("users", "oauth_provider")
    op.drop_column("users", "is_admin")

    oauth_provider_enum = postgresql.ENUM("GITHUB", "GOOGLE", name="oauthprovider")
    oauth_provider_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
