"""Add index on is_public field

Revision ID: 453326bf7956
Revises: d5903d99331a
Create Date: 2025-11-12 02:46:22.900863

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "453326bf7956"
down_revision: Union[str, None] = "d5903d99331a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_datasets_is_public"), "datasets", ["is_public"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_datasets_is_public"), table_name="datasets")
    # ### end Alembic commands ###
