"""empty message

Revision ID: 5bec74691db9
Revises: 7db414c9b3d4
Create Date: 2025-03-11 22:44:02.829739

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "5bec74691db9"
down_revision: Union[str, None] = "7db414c9b3d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
