"""empty message

Revision ID: 9eb101b46037
Revises: 85d6c79df790
Create Date: 2025-03-27 14:27:42.790097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9eb101b46037"
down_revision: Union[str, None] = "85d6c79df790"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tasks", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "owner_id")
    # ### end Alembic commands ###
