"""empty message

Revision ID: 8062abfea43d
Revises: 9eb101b46037
Create Date: 2025-03-27 23:15:02.682518

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8062abfea43d"
down_revision: Union[str, None] = "9eb101b46037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filetasklinks",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("file_id", "task_id"),
    )
    op.add_column("tasks", sa.Column("initiator_id", sa.Integer(), nullable=True))
    op.drop_constraint("tasks_owner_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(None, "tasks", "users", ["initiator_id"], ["id"])
    op.drop_column("tasks", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key("tasks_owner_id_fkey", "tasks", "users", ["owner_id"], ["id"])
    op.drop_column("tasks", "initiator_id")
    op.drop_table("filetasklinks")
    # ### end Alembic commands ###
