"""empty message

Revision ID: e0dfc8e7f2e8
Revises: 43c792ffabae
Create Date: 2025-08-18 18:43:45.949039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0dfc8e7f2e8"
down_revision: Union[str, None] = "43c792ffabae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("params", sa.JSON(), nullable=False))
    op.drop_column("tasks", "config")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tasks", "params")
    # ### end Alembic commands ###
