"""empty message

Revision ID: 8442ef8218af
Revises: cfbdb327e6e9
Create Date: 2025-09-02 22:34:30.416473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "8442ef8218af"
down_revision: Union[str, None] = "cfbdb327e6e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("taskresults_task_id_key"), "taskresults", type_="unique")
    op.add_column(
        "tasks",
        sa.Column("info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "info")
    op.create_unique_constraint(
        op.f("taskresults_task_id_key"),
        "taskresults",
        ["task_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
