"""empty message

Revision ID: e07f6a024002
Revises: 370045205bec
Create Date: 2026-03-13 18:00:05.431770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e07f6a024002"
down_revision: Union[str, None] = "370045205bec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasettasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=155), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("date_done", sa.DateTime(timezone=True), nullable=True),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.add_column(
        "datasets",
        sa.Column("preprocess_task_id", sa.String(length=155), nullable=True),
    )
    op.create_index(
        op.f("ix_datasets_preprocess_task_id"),
        "datasets",
        ["preprocess_task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_datasets_preprocess_task_id"), table_name="datasets")
    op.drop_column("datasets", "preprocess_task_id")
    op.drop_table("datasettasks")
    # ### end Alembic commands ###
