"""empty message

Revision ID: c6ba3930e674
Revises: 3b862a42cce4
Create Date: 2026-03-18 03:39:10.840848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c6ba3930e674"
down_revision: Union[str, None] = "3b862a42cce4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "preprocessingtasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "RECEIVED",
            "STARTED",
            "SUCCESS",
            "FAILURE",
            "RETRY",
            "REVOKED",
            name="celerytaskstatus",
        ),
        type_=sa.Enum(
            "PENDING",
            "RECEIVED",
            "STARTED",
            "SUCCESS",
            "FAILURE",
            "RETRY",
            "REVOKED",
            name="celerytaskstatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.add_column(
        "tasks", sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "PROCESSING", "SUCCESS", "FAILED", name="taskstatus"
        ),
        type_=sa.Enum(
            "PENDING",
            "RECEIVED",
            "STARTED",
            "SUCCESS",
            "FAILURE",
            "RETRY",
            "REVOKED",
            name="celerytaskstatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "RECEIVED",
            "STARTED",
            "SUCCESS",
            "FAILURE",
            "RETRY",
            "REVOKED",
            name="celerytaskstatus",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "PENDING", "PROCESSING", "SUCCESS", "FAILED", name="taskstatus"
        ),
        existing_nullable=False,
    )
    op.drop_column("tasks", "finished_at")
    op.alter_column(
        "preprocessingtasks",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "RECEIVED",
            "STARTED",
            "SUCCESS",
            "FAILURE",
            "RETRY",
            "REVOKED",
            name="celerytaskstatus",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "PENDING",
            "RECEIVED",
            "STARTED",
            "SUCCESS",
            "FAILURE",
            "RETRY",
            "REVOKED",
            name="celerytaskstatus",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
