"""empty message

Revision ID: 55ba69269d2b
Revises: e07f6a024002
Create Date: 2026-03-13 22:21:32.919320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "55ba69269d2b"
down_revision: Union[str, None] = "e07f6a024002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preprocessingtasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RECEIVED",
                "STARTED",
                "SUCCESS",
                "FAILURE",
                "RETRY",
                "REVOKED",
                name="celerytaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_preprocessingtasks_dataset_id"),
        "preprocessingtasks",
        ["dataset_id"],
        unique=True,
    )
    op.drop_table("datasettasks")
    op.drop_index(op.f("ix_datasets_preprocess_task_id"), table_name="datasets")
    op.drop_column("datasets", "preprocess_task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column(
            "preprocess_task_id",
            sa.VARCHAR(length=155),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_datasets_preprocess_task_id"),
        "datasets",
        ["preprocess_task_id"],
        unique=False,
    )
    op.create_table(
        "datasettasks",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=False
        ),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "date_done",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("traceback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("datasettasks_pkey")),
        sa.UniqueConstraint(
            "task_id",
            name=op.f("datasettasks_task_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index(
        op.f("ix_preprocessingtasks_dataset_id"), table_name="preprocessingtasks"
    )
    op.drop_table("preprocessingtasks")
    # ### end Alembic commands ###
