"""empty message

Revision ID: 7be8e08d8fa8
Revises: d85315d0789c
Create Date: 2026-03-01 11:42:33.023499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7be8e08d8fa8"
down_revision: Union[str, None] = "d85315d0789c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
