"""empty message

Revision ID: 93641ed7438c
Revises: c48df84651bc
Create Date: 2026-02-08 03:22:57.499911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "93641ed7438c"
down_revision: Union[str, None] = "c48df84651bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_failure_reason_enum = postgresql.ENUM(
        "MEMORY_LIMIT_EXCEEDED",
        "TIME_LIMIT_EXCEEDED",
        "WORKER_KILLED_BY_SIGNAL",
        "OTHER",
        name="taskfailurereason",
        create_type=True,
    )
    task_failure_reason_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "tasks", sa.Column("raised_exception_name", sa.String(), nullable=True)
    )
    op.add_column(
        "tasks", sa.Column("failure_reason", task_failure_reason_enum, nullable=True)
    )
    op.add_column("tasks", sa.Column("traceback", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "traceback")
    op.drop_column("tasks", "failure_reason")
    op.drop_column("tasks", "raised_exception_name")

    task_failure_reason_enum = postgresql.ENUM(
        "MEMORY_LIMIT_EXCEEDED",
        "TIME_LIMIT_EXCEEDED",
        "WORKER_KILLED_BY_SIGNAL",
        "OTHER",
        name="taskfailurereason",
    )
    task_failure_reason_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
