"""empty message

Revision ID: d85315d0789c
Revises: 3c339dd8e702
Create Date: 2026-02-28 20:56:05.298193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d85315d0789c"
down_revision: Union[str, None] = "3c339dd8e702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column(
            "status",
            sa.Enum("uploading", "ready", name="datasetstatus", native_enum=False),
            nullable=False,
        ),
    )
    op.add_column("tasks", sa.Column("is_public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_public")
    op.drop_column("datasets", "status")
    # ### end Alembic commands ###
