"""empty message

Revision ID: a17203b3c082
Revises: 93641ed7438c
Create Date: 2026-02-13 02:05:57.526938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "a17203b3c082"
down_revision: Union[str, None] = "93641ed7438c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "status")
    op.drop_column("datasets", "info")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column(
            "info",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "datasets",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "PROCESSING", "SUCCESS", "FAILED", name="taskstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
