"""empty message

Revision ID: 3b862a42cce4
Revises: 55ba69269d2b
Create Date: 2026-03-18 01:52:39.974838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3b862a42cce4"
down_revision: Union[str, None] = "55ba69269d2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "info")
    op.drop_column("datasets", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column("status", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    )
    op.add_column(
        "datasets",
        sa.Column(
            "info",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
