"""empty message

Revision ID: c556b5e7e802
Revises: 60640a3c9d74
Create Date: 2026-03-18 22:49:47.413014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c556b5e7e802"
down_revision: Union[str, None] = "60640a3c9d74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("datasets", sa.Column("is_uploaded", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_datasets_is_uploaded"), "datasets", ["is_uploaded"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_datasets_is_uploaded"), table_name="datasets")
    op.drop_column("datasets", "is_uploaded")
    # ### end Alembic commands ###
