"""empty message

Revision ID: 3c339dd8e702
Revises: a17203b3c082
Create Date: 2026-02-26 00:36:02.831861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3c339dd8e702"
down_revision: Union[str, None] = "a17203b3c082"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authaccounts",
        sa.Column(
            "provider",
            sa.Enum("github", "google", name="authprovider", native_enum=False),
            nullable=False,
        ),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("provider", "account_id"),
    )
    op.create_index(
        op.f("ix_authaccounts_owner_id"), "authaccounts", ["owner_id"], unique=False
    )
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=False))
    op.drop_constraint("uq_user_oauth", "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "oauth_provider")
    op.drop_column("users", "oauth_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("oauth_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "oauth_provider",
            postgresql.ENUM("GITHUB", "GOOGLE", name="oauthprovider"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        "uq_user_oauth", "users", ["oauth_provider", "oauth_id"]
    )
    op.drop_column("users", "email")
    op.drop_index(op.f("ix_authaccounts_owner_id"), table_name="authaccounts")
    op.drop_table("authaccounts")
    # ### end Alembic commands ###
