"""empty message

Revision ID: 370045205bec
Revises: 7be8e08d8fa8
Create Date: 2026-03-10 03:30:01.913726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "370045205bec"
down_revision: Union[str, None] = "7be8e08d8fa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_dataset_links",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "dataset_id"),
    )
    op.create_table(
        "taskresults",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "datasets",
        sa.Column("info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "datasets",
        "status",
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum(
            "pending",
            "processing",
            "success",
            "failed",
            name="taskstatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.add_column(
        "tasks",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.drop_constraint(op.f("tasks_dataset_id_fkey"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "traceback")
    op.drop_column("tasks", "raised_exception_name")
    op.drop_column("tasks", "dataset_id")
    op.drop_column("tasks", "config")
    op.drop_column("tasks", "failure_reason")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "failure_reason",
            postgresql.ENUM(
                "MEMORY_LIMIT_EXCEEDED",
                "TIME_LIMIT_EXCEEDED",
                "WORKER_KILLED_BY_SIGNAL",
                "OTHER",
                name="taskfailurereason",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tasks", sa.Column("dataset_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "tasks",
        sa.Column(
            "raised_exception_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tasks",
        sa.Column("traceback", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("tasks_dataset_id_fkey"),
        "tasks",
        "datasets",
        ["dataset_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("tasks", "params")
    op.alter_column(
        "datasets",
        "status",
        existing_type=sa.Enum(
            "pending",
            "processing",
            "success",
            "failed",
            name="taskstatus",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    op.drop_column("datasets", "info")
    op.drop_table("taskresults")
    op.drop_table("task_dataset_links")
    # ### end Alembic commands ###
