from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from aioredlock.algorithm import Aioredlock

class Lock:
    lock_manager: Aioredlock
    resource: str
    id: str
    lock_timeout: float
    valid: bool

    def __init__(
        self,
        lock_manager: Aioredlock,
        resource: str,
        id: str,
        lock_timeout: float = 10.0,
        valid: bool = False,
    ) -> None: ...
    async def __aenter__(self) -> Lock: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    async def extend(self) -> None: ...
    async def release(self) -> None: ...
    async def is_locked(self) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
