name: base
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  run-linters-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: python3 -m pip install poetry==1.6.1 && make init

      - name: Run all linters and formatters
        run: make lint

      - name: Up all containers
        run: docker compose -f dev-docker-compose.yaml up --build --force-recreate --remove-orphans -d

      - name: Run all tests and count coverage
        run: make test
