name: Lint
on:
  pull_request:
  push:
jobs:
  run-linters-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: python3 -m pip install poetry==1.8.2 && make init

      - name: Run all linters and formatters
        run: make lint

      - name: Run type check
        run: make check-types

      - name: Up all containers
        run: docker compose -f dev-docker-compose.yaml up --build --force-recreate --remove-orphans -d

      - name: Run all tests and count coverage
        run: make test
